/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_EVENT_PB_H_INCLUDED
#define PB_EVENT_PB_H_INCLUDED
#include "ProtoBuf/pb.h"
#include "ProtoBuf/header.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(256) Event_payload_t;
typedef struct _Event {
    bool has_header;
    Header header;
    Event_payload_t payload;
} Event;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Event_init_default                       {false, Header_init_default, {0, {0}}}
#define Event_init_zero                          {false, Header_init_zero, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define Event_header_tag                         1
#define Event_payload_tag                        2

/* Struct field encoding specification for nanopb */
#define Event_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           2)
#define Event_CALLBACK NULL
#define Event_DEFAULT NULL
#define Event_header_MSGTYPE Header

extern const pb_msgdesc_t Event_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Event_fields &Event_msg

/* Maximum encoded size of messages (where known) */
#define Event_size                               462

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
