#ifndef __DEV_REG_CONFIG_H__
#define __DEV_REG_CONFIG_H__

#define IOTEX_TOKEN_DEFAULT				"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQYXlsb2FkIjoiOTAyNzQ2OTkzNTA1NzkyNyIsImlzcyI6InczYnN0cmVhbSJ9.ukIZOLshfnwuVa3LUSTJIQdJvnEQUDHSLOsqJKcfDOI"
#define IOTEX_MQTT_TOPIC_DEFAULT		"eth_0x31c3785bebe03cc5ba691c486d6d1cdf8bb438c4_esp32_verify"

#endif /* __DEV_REG_CONFIG_H__ */
